sudo: false
language: scala
jdk:
  - oraclejdk8
before_install:
  - npm install
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
  - sbt build
